### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by tinobragaa** [tinobragaa/hackathon-team1-april#19]
As a user, I would like to be able to sign up, so that I can network with other users in the Eire Settlers community.

### Acceptance Criteria
- Users can register.
- Users can log in.
- Users can log out.

### Tasks
- [x] Install django-allauth package.
- [x] Copy allauth templates into root template directory.
- [x] Update settings.py with allauth settings.
