### ISSUE TITLE
Edit Post Functionality

### ISSUE THREAD

**Issue by tinobragaa** [tinobragaa/hackathon-team1-april#47]
As a user, I would like to be able to edit my post when I want to make changes to its content.

### Acceptance Criteria
- Users should have access to an "Edit" button next to their published posts.
- Users should be able to modify the information of the post.
- After making changes, users should be able to save and update the post with the edited content.

### Tasks
- [x] Create template.
- [x] Create a form to edit post content.
- [x] Develop a view to handle post editing.
- [x] Configure URL routing for post editing.
