### ISSUE TITLE
Create Basic File Structure

### ISSUE THREAD

**Issue by tinobragaa** [tinobragaa/hackathon-team1-april#8]
As a **role** I want to be able to **action** so that I can **received benefit**.

### Acceptance Criteria
- Base HTML created
- Static resources created

### Tasks
- [x] Create HTML file
- [x] Create a static folder with sub directories CSS, images and JS
- [x] Create style.css and link to html
